name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  client:
    name: Client Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install dependencies
      working-directory: ./client
      run: npm install

    # - name: Run tests
    #   working-directory: ./client
    #   run: npm test

    - name: Build the project
      working-directory: ./client
      run: npm run build

  server:
    name: Server Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install dependencies
      working-directory: ./server
      run: npm install

    # - name: Run tests
    #   working-directory: ./server
    #   run: npm test

