name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  client-lint:
    name: Lint Client Code
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      working-directory: ./client
      run: npm install

    - name: Run ESLint
      working-directory: ./client
      run: npm run lint

  # server-lint:
  #   name: Lint Server Code
  #   runs-on: ubuntu-latest
  #   continue-on-error: true

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Use Node.js 18.x
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: 18.x

  #   - name: Install dependencies
  #     working-directory: ./server
  #     run: npm install

  #   - name: Run ESLint
  #     working-directory: ./server
  #     run: npm run lint
